api/src/main/java/org/yapp/domain/auth/api/LoginController.java, api/src/main/java/org/yapp/domain/auth/application/jwt/JwtFilter.java, api/src/main/java/org/yapp/domain/auth/application/jwt/JwtUtil.java, api/src/main/java/org/yapp/domain/auth/application/oauth/OauthClient.java, api/src/main/java/org/yapp/domain/auth/application/oauth/OauthProvider.java, api/src/main/java/org/yapp/domain/auth/application/oauth/OauthProviderResolver.java, api/src/main/java/org/yapp/domain/auth/application/oauth/google/GoogleOauthClient.java, api/src/main/java/org/yapp/domain/auth/application/oauth/google/GoogleOauthProvider.java, api/src/main/java/org/yapp/domain/auth/application/oauth/kakao/KakaoOauthClient.java, api/src/main/java/org/yapp/domain/auth/application/oauth/kakao/KakaoOauthProvider.java, api/src/main/java/org/yapp/domain/auth/application/oauth/service/OauthService.java, api/src/main/java/org/yapp/domain/auth/domain/enums/OauthType.java, api/src/main/java/org/yapp/domain/auth/dto/request/OauthLoginRequest.java, api/src/main/java/org/yapp/domain/auth/dto/response/OauthLoginResponse.java, api/src/main/java/org/yapp/domain/auth/dto/response/OauthUserInfoResponse.java, api/src/main/java/org/yapp/domain/user/dao/UserRepository.java, api/src/main/java/org/yapp/domain/user/domain/User.java, api/src/main/java/org/yapp/global/config/RestTemplateConfig.java, api/src/main/java/org/yapp/global/config/SecurityConfig.java, api/src/main/resources/application.yml, api/src/test/java/org/yapp/domain/auth/application/jwt/JwtUtilTest.java, api/src/test/java/org/yapp/domain/auth/application/oauth/OauthProviderResolverTest.java, api/src/test/java/org/yapp/domain/auth/application/oauth/google/GoogleOauthClientTest.java, api/src/test/java/org/yapp/domain/auth/application/oauth/google/GoogleOauthProviderTest.java, api/src/test/java/org/yapp/domain/auth/application/oauth/kakao/KakaoOauthClientTest.java, api/src/test/java/org/yapp/domain/auth/application/oauth/kakao/KakaoOauthProviderTest.java, api/src/test/java/org/yapp/domain/auth/application/oauth/service/OauthServiceTest.java, build.gradle
=> feature : Login - Oauth 2.0 구조 설계 및 Kakao,Google 로그인 기능 구현

api/build.gradle, api/src/main/java/org/yapp/health/HealthCheckController.java, build.gradle, common/build.gradle, common/src/main/java/org/yapp/config/SwaggerConfig.java, common/src/main/java/org/yapp/error/GlobalExceptionHandler.java, common/src/main/java/org/yapp/error/dto/CommonErrorCode.java, common/src/main/java/org/yapp/error/dto/ErrorCode.java, common/src/main/java/org/yapp/error/dto/ErrorResponse.java, common/src/main/java/org/yapp/error/dto/SecurityErrorCode.java, common/src/main/java/org/yapp/error/dto/UserErrorCode.java, common/src/main/java/org/yapp/error/exception/ApplicationException.java
#3 
- swagger 설정
- 전역 예외 처리기 설정
=> Feat: config - configure project

api/src/main/java/org/yapp/domain/auth/api/LoginController.java, api/src/main/java/org/yapp/global/common/dto/ApiResponse.java
#3 
- 공통 응답 형식 추가
- 로그인 컨트롤러 공통 응답 형식 적용
=> Feature: 공통 응답 형식 추가 (#PC-31)

api/src/main/java/org/yapp/domain/profile/application/ProfileService.java, api/src/main/java/org/yapp/domain/profile/dao/ProfileRepository.java, api/src/main/java/org/yapp/domain/profile/dao/ProfileValueRepository.java, api/src/main/java/org/yapp/domain/profile/presentation/ProfileController.java, api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileValuePair.java, api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileValueUpdateRequest.java, api/src/test/java/org/yapp/domain/auth/application/profile/ProfileServiceTest.java, common/src/main/java/org/yapp/domain/profile/Profile.java, common/src/main/java/org/yapp/domain/profile/ProfileValue.java
[PC-209](https://yapp25app3.atlassian.net/browse/PC-209)
- DB에 중복되는 이름이 있는지 확인하는 기능
[PC-209]: https://yapp25app3.atlassian.net/browse/PC-209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-209] 닉네임 중복 확인 기능

api/src/main/java/org/yapp/domain/auth/presentation/SmsAuthController.java, api/src/main/java/org/yapp/domain/term/applicatoin/TermUseCase.java, api/src/main/java/org/yapp/domain/term/presentation/TermController.java, api/src/main/java/org/yapp/domain/term/presentation/dto/request/TermAgreementRequest.java, api/src/main/java/org/yapp/domain/term/presentation/dto/response/TermResponse.java, api/src/main/resources/application.yml, common/src/main/java/org/yapp/domain/term/Term.java, common/src/main/java/org/yapp/error/dto/TermErrorCode.java, common/src/main/java/org/yapp/util/CommonResponse.java, docker-compose.yml
[PC-290](https://yapp25app3.atlassian.net/browse/PC-290)
- 도커 컴포즈 레디스 추가
- 제네릭 타입 없는 응답 수정
- 약관 등록 API 
[PC-290]: https://yapp25app3.atlassian.net/browse/PC-290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-290] 회원가입 로직 점검

api/src/main/java/org/yapp/domain/auth/presentation/LoginController.java, api/src/main/java/org/yapp/domain/auth/presentation/SmsAuthController.java
[PC-294](https://yapp25app3.atlassian.net/browse/PC-294)
- 로그인 API Swagger 설정
- SMS 인증 API Swagger 설정
[PC-294]: https://yapp25app3.atlassian.net/browse/PC-294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-294] 로그인/SMS인증 API Swagger 설정

api/src/main/java/org/yapp/domain/block/application/BlockService.java, api/src/main/java/org/yapp/domain/block/application/dto/BlockCreateDto.java, api/src/main/java/org/yapp/domain/block/dao/BlockRepository.java, api/src/main/java/org/yapp/domain/block/presentation/BlockController.java, api/src/main/java/org/yapp/domain/block/presentation/dto/request/BlockPhoneNumbersRequest.java, api/src/main/java/org/yapp/domain/block/presentation/dto/response/BlockResponse.java, api/src/main/java/org/yapp/domain/block/presentation/dto/response/UserBlockResponses.java, api/src/main/java/org/yapp/domain/profile/presentation/ProfileController.java, api/src/main/java/org/yapp/domain/term/presentation/TermController.java, api/src/main/java/org/yapp/domain/value/presentation/ValueItemController.java, api/src/main/resources/init.sql, common/src/main/java/org/yapp/config/JpaConfig.java, common/src/main/java/org/yapp/domain/BaseEntity.java, common/src/main/java/org/yapp/domain/block/Block.java, common/src/main/java/org/yapp/domain/user/User.java, common/src/main/java/org/yapp/util/CommonResponse.java
[PC-293](https://yapp25app3.atlassian.net/browse/PC-293)
- user 테이블먕 수정 (user_common -> user_table) 
- blocked_contacts 테이블, block 도메인 추가
- 핸드폰 차단 등록 API
- 등록된 차단 핸드폰 조회 API
[PC-293]: https://yapp25app3.atlassian.net/browse/PC-293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-293] 차단 핸드폰 번호 추가 및 조회

api/src/main/java/org/yapp/ApiApplication.java, api/src/main/java/org/yapp/domain/match/application/MatchService.java, api/src/main/java/org/yapp/domain/match/application/algorithm/PreferenceBasedMatchingAlgorithm.java, api/src/main/java/org/yapp/domain/match/application/blocker/AcquaintanceBasedBlocker.java, api/src/main/java/org/yapp/domain/match/application/blocker/Blocker.java, api/src/main/java/org/yapp/domain/match/application/blocker/DirectBlockBasedBlocker.java, api/src/main/java/org/yapp/domain/match/application/blocker/PreviousMatchBlocker.java, api/src/main/java/org/yapp/domain/match/application/matcher/CoupleMatcher.java, api/src/main/java/org/yapp/domain/match/application/matcher/PreferenceBasedMatcher.java, api/src/main/java/org/yapp/domain/match/batch/MatchScheduler.java, api/src/main/java/org/yapp/domain/match/dao/MatchInfoRepository.java, api/src/main/java/org/yapp/domain/profile/application/ProfileService.java, api/src/main/java/org/yapp/domain/profile/application/ProfileValuePickService.java, api/src/main/java/org/yapp/domain/profile/dao/ProfileRepository.java, api/src/main/java/org/yapp/domain/profile/dao/ProfileValuePickRepository.java, api/src/main/java/org/yapp/domain/profile/enums/Location.java, common/src/main/java/org/yapp/domain/match/MatchInfo.java, common/src/main/java/org/yapp/domain/user/User.java, common/src/main/java/org/yapp/error/dto/MatchErrorCode.java
[PC-267](https://yapp25app3.atlassian.net/browse/PC-267)
- 매칭 구조 설계
- 차단 기능 책임연쇄패턴으로 설계
- 가치관 기반 매칭기 구현
- 매칭 알고리즘 구조 설계
[PC-267]: https://yapp25app3.atlassian.net/browse/PC-267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PC-267]: https://yapp25app3.atlassian.net/browse/PC-267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-267] 매칭 기능 구조 설계 및 일부 구현

api/src/main/java/org/yapp/domain/block/application/DirectBlockService.java, api/src/main/java/org/yapp/domain/block/dao/DirectBlockRepository.java, api/src/main/java/org/yapp/domain/match/application/MatchService.java, api/src/main/java/org/yapp/domain/match/application/blocker/DirectBlockBasedBlocker.java, api/src/main/java/org/yapp/domain/match/presentation/MatchController.java, api/src/main/java/org/yapp/domain/match/presentation/dto/response/ContactResponse.java, common/src/main/java/org/yapp/domain/block/DirectBlock.java, common/src/main/java/org/yapp/domain/match/MatchInfo.java, common/src/main/java/org/yapp/error/dto/MatchErrorCode.java
[PC-271](https://yapp25app3.atlassian.net/browse/PC-271)
- 매칭 수락 기능 구현
- 매칭 상대 연락처 조회 기능 구현
[PC-271]: https://yapp25app3.atlassian.net/browse/PC-271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-271] 매칭 수락 기능 및 연락처 조회 기능 구현

api/src/main/java/org/yapp/domain/report/application/ReportService.java, api/src/main/java/org/yapp/domain/report/controller/ReportController.java, api/src/main/java/org/yapp/domain/report/dao/ReportRepository.java, api/src/main/java/org/yapp/domain/report/dto/request/UserReportRequest.java, common/src/main/java/org/yapp/error/dto/ReportErrorCode.java
[PC-272](https://yapp25app3.atlassian.net/browse/PC-272)
- 유저 신고 기능 구현
[PC-272]: https://yapp25app3.atlassian.net/browse/PC-272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-272] 유저 신고 기능 구현

api/src/main/java/org/yapp/domain/match/application/MatchService.java, api/src/main/java/org/yapp/domain/match/presentation/MatchController.java, api/src/main/java/org/yapp/domain/match/presentation/dto/response/ContactResponse.java, api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileBasicUpdateRequest.java, api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileCreateRequest.java, api/src/main/java/org/yapp/domain/profile/presentation/response/ProfileBasicResponse.java, core/build.gradle, core/domain/src/main/java/org/yapp/core/domain/profile/ContactType.java, core/domain/src/main/java/org/yapp/core/domain/profile/Profile.java, core/domain/src/main/java/org/yapp/core/domain/profile/ProfileBasic.java, infra/build.gradle
[PC-000] 
- 연락처를 관리할 때 , key 값에 ContactType을 사용하도록 변경했습니다.
- 프로필 업데이트 dto 에 흡연, sns 정보 데이터에 NotBlank 제약 조건을 추가했습니다.
=> [PC-000] 프로필 연락처 타입 수정

api/src/main/java/org/yapp/domain/profile/application/ProfileImageService.java, api/src/main/java/org/yapp/domain/profile/presentation/ProfileController.java, core/exception/src/main/java/org/yapp/core/exception/error/code/ProfileErrorCode.java
[PC-518](https://yapp25app3.atlassian.net/browse/PC-518)
- 프로필 이미지 등록 스웨거 명확하게 수정
- 프로필 이미지 MIME TYPE 제한
[PC-518]: https://yapp25app3.atlassian.net/browse/PC-518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-518] 프로필 이미지 등록 설정 수정

api/src/main/java/org/yapp/domain/block/application/BlockContactService.java, api/src/main/java/org/yapp/domain/block/presentation/BlockContactController.java
=> [PC-000] fix: 차단 핸드폰 번호 리스트 조회 swagger 수정

api/src/main/java/org/yapp/domain/match/presentation/MatchController.java, api/src/main/java/org/yapp/domain/profile/application/ProfileService.java, api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileBasicUpdateRequest.java, api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileCreateRequest.java, api/src/main/java/org/yapp/domain/profile/presentation/response/ContactResponse.java, api/src/main/java/org/yapp/domain/profile/presentation/response/ContactResponses.java, api/src/main/java/org/yapp/domain/profile/presentation/response/ProfileBasicResponse.java, api/src/main/java/org/yapp/domain/profile/presentation/validation/ContactTypeValidator.java, api/src/main/java/org/yapp/domain/profile/presentation/validation/ValidContactType.java
[PC-547](https://yapp25app3.atlassian.net/browse/PC-547)
- Contact를 생성/업데이트 하는 경우, ContactType을 검증하는 로직 추가
- Contsct 데이터 클라이언트로 전달하는 경우 List로 변환
[PC-547]: https://yapp25app3.atlassian.net/browse/PC-547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-547] 연락처 데이터 리스트 전달

api/src/main/java/org/yapp/domain/auth/presentation/LoginController.java, api/src/main/java/org/yapp/domain/auth/presentation/dto/request/TokenHealthCheckRequest.java, api/src/main/java/org/yapp/domain/match/application/MatchService.java, api/src/main/java/org/yapp/domain/match/presentation/dto/response/MatchInfoResponse.java, api/src/main/java/org/yapp/domain/match/presentation/dto/response/MatchValuePickInnerResponse.java
[PC-553](https://yapp25app3.atlassian.net/browse/PC-553)
- 토큰 헬스 체크 API 수정
- 같은 가치관 변수명 수정
- 가치관 응답 일치 여부 변수명 수정
- ValuePick Map->List 형식으로 변경
- MatchInfo에 매칭상대 userId 추가
[PC-553]: https://yapp25app3.atlassian.net/browse/PC-553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-553] 코드 세부 수정사항 반영

api/src/main/java/org/yapp/domain/profile/enums/Location.java
[PC-581](https://yapp25app3.atlassian.net/browse/PC-581)
- 활동지역 enum 추가
[PC-581]: https://yapp25app3.atlassian.net/browse/PC-581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-581] 활동지역 ENUM 추가

api/src/main/java/org/yapp/domain/block/application/BlockContactService.java, api/src/main/java/org/yapp/domain/setting/application/BlockContactSyncTimeService.java, api/src/main/java/org/yapp/domain/setting/dao/BlockContactSyncTimeRepository.java, api/src/main/java/org/yapp/domain/setting/dto/response/BlockContactSyncTimeResponse.java, api/src/main/java/org/yapp/domain/setting/presentation/SettingController.java, core/domain/src/main/java/org/yapp/core/domain/setting/BlockContactSyncTime.java, core/exception/src/main/java/org/yapp/core/exception/error/code/BlockContactErrorCode.java
[PC-598](https://yapp25app3.atlassian.net/browse/PC-598)
- 연락처 동기화 시간 엔티티 추가
- 연락처 동기화 시간 기록 기능 구현
- 연락처 동기화 시간 조회 기능 구현
[PC-598]: https://yapp25app3.atlassian.net/browse/PC-598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-598] 차단 연락처 동기화 시간 조회 기능 추가

api/src/main/java/org/yapp/domain/auth/application/oauth/service/LogoutService.java, api/src/main/java/org/yapp/domain/auth/presentation/LogoutController.java, core/auth/src/main/java/org/yapp/core/auth/token/RefreshTokenService.java
[PC-582](https://yapp25app3.atlassian.net/browse/PC-582)
- 로그아웃 기능 구현
- 로그아웃 시 리프레시 토큰 삭제
[PC-582]: https://yapp25app3.atlassian.net/browse/PC-582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-582] 로그아웃 기능 구현

api/src/main/java/org/yapp/domain/user/application/UserService.java
[PC-623](https://yapp25app3.atlassian.net/browse/PC-623)
- 회원가입 진행시(번호 인증, 프로필 등록 AuthTokenGenerator를 사용하여 토큰을 발급하도록 수정
[PC-623]: https://yapp25app3.atlassian.net/browse/PC-623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-623] fix: 회원가입 진행시 토큰 발급 로직 수정 (AuthTokenGenerator 사용)

api/src/main/java/org/yapp/global/config/SecurityConfig.java, core/auth/src/main/java/org/yapp/core/auth/jwt/JwtFilter.java, core/auth/src/main/java/org/yapp/core/auth/jwt/JwtUtil.java, core/exception/src/main/java/org/yapp/core/exception/GlobalExceptionHandler.java
[PC-625](https://yapp25app3.atlassian.net/browse/PC-625)
- 액세스 토큰 만료시 에러 코드 401로 보내도록 수정
- 접근 권한 예외 처리
- 메서드 시큐리티 설정 추가
[PC-625]: https://yapp25app3.atlassian.net/browse/PC-625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-625] 시큐리티 필터 예외 처리

api/src/main/java/org/yapp/domain/auth/application/oauth/OauthClient.java, api/src/main/java/org/yapp/domain/auth/application/oauth/OauthProvider.java, api/src/main/java/org/yapp/domain/auth/application/oauth/apple/AppleOauthClient.java, api/src/main/java/org/yapp/domain/auth/application/oauth/google/GoogleOauthClient.java, api/src/main/java/org/yapp/domain/auth/application/oauth/kakao/KakaoOauthClient.java, api/src/main/java/org/yapp/domain/auth/application/oauth/service/OauthService.java, api/src/main/java/org/yapp/domain/user/presentation/UserController.java, api/src/main/java/org/yapp/domain/user/presentation/dto/request/OauthUserDeleteRequest.java, core/domain/src/main/java/org/yapp/core/domain/user/User.java
[PC-632](https://yapp25app3.atlassian.net/browse/PC-632)
- OauthProvider#unlink 추가
- OauthClient#unlink 추가
- AppleOauthClient#unlink 구현
- 소셜 회원 탈퇴 컨트롤러 메서드 구현
[PC-632]: https://yapp25app3.atlassian.net/browse/PC-632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-632] 애플 회원 탈퇴

api/src/main/java/org/yapp/domain/user/application/UserService.java, api/src/main/java/org/yapp/domain/user/presentation/UserController.java, api/src/main/java/org/yapp/domain/user/presentation/dto/response/UserBasicInfoResponse.java
[PC-684]
- 유저 기본 정보 조회 기능 구현
[PC-684]: https://yapp25app3.atlassian.net/browse/PC-684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-684] 유저 기본 정보 조회 API 추가

core/auth/src/main/java/org/yapp/core/auth/token/RefreshTokenService.java
[PC-722]
- 토큰 refresh 로직에서 refreshToken 만료시 에러 처리
[PC-722]: https://yapp25app3.atlassian.net/browse/PC-722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-722] 토큰 refresh 로직에서 refreshToken 만료시 에러 처리

api/src/main/java/org/yapp/domain/notification/application/NotificationHistoryService.java, api/src/main/java/org/yapp/domain/notification/dto/request/NotificationRequest.java, api/src/main/java/org/yapp/domain/notification/dto/response/NotificationHistoryResponse.java, api/src/main/java/org/yapp/domain/notification/presentation/NotificationCenterController.java, core/domain/src/main/java/org/yapp/core/domain/notification/NotificationHistory.java, core/exception/src/main/java/org/yapp/core/exception/error/code/NotificationErrorCode.java
[PC-719]
- 알람 정보 dateTime 추가
[PC-719]: https://yapp25app3.atlassian.net/browse/PC-719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-719] 알람 정보 dateTime 추가

api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileBasicUpdateRequest.java, api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileCreateRequest.java, api/src/main/java/org/yapp/domain/profile/presentation/response/ProfileValuePickResponse.java, api/src/main/java/org/yapp/domain/profile/presentation/response/ProfileValuePickResponses.java, api/src/main/java/org/yapp/domain/profile/presentation/response/ProfileValueTalkResponse.java
[PC-710](https://yapp25app3.atlassian.net/browse/PC-710)
- ProfileBasicUpdateRequest Contacts 필드 설명 변경
- ProfileUpdateRequest.birthdate 타입 변경 (string -> LocalDate) 및 Not Null 제약 조건 추가
- 프로필 Pick 조회시 원본 질문 식별값 전달
- 프로필 Talk 조회시 원본 질문 식별값 전달
[PC-710]: https://yapp25app3.atlassian.net/browse/PC-710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-710] 가치관 Pick / Talk 원본 질문 식별값 데이터 전달

api/src/main/java/org/yapp/domain/setting/dto/response/BlockContactSyncTimeResponse.java
[PC-791]
- 연락처 차단 동기화 시간 형식 변경
[PC-791]: https://yapp25app3.atlassian.net/browse/PC-791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-791] 연락처 차단 동기화 시간 형식 변경

api/src/main/java/org/yapp/domain/profile/application/ProfileService.java, api/src/main/java/org/yapp/domain/profile/application/ProfileValueTalkSummaryService.java, api/src/main/java/org/yapp/domain/profile/application/dto/ProfileValueTalkAnswerDto.java, api/src/main/java/org/yapp/domain/profile/presentation/ProfileController.java, infra/ai/src/main/java/org/yapp/infra/ai/application/ClovaChatSummarizationService.java
[PC-788](https://yapp25app3.atlassian.net/browse/PC-788)
- 요약 API 호출 실패시 처리
- 수정된 응답에 대해서만 요약 API 호출
[PC-788]: https://yapp25app3.atlassian.net/browse/PC-788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-788] 요약 기능 리팩토링

admin/src/main/java/org/yapp/user/application/UserService.java
=> [PC-812] fix: 프로필 상태가 승인 상태인 경우, 리젝사유를 모두 false로 설정

.github/workflows/cicd-admin-prod.yml
=> [PC-000] feat: 운영환경 어드민 ci/cd 파이어베이스 json 로딩 과정 추가

.github/workflows/cicd-admin-prod.yml, .github/workflows/cicd-dev.yml, api/src/main/java/org/yapp/domain/auth/application/authorization/SmsAuthService.java, api/src/main/java/org/yapp/domain/auth/presentation/SmsAuthController.java, api/src/main/java/org/yapp/domain/auth/presentation/dto/response/SmsAuthResponse.java, api/src/main/java/org/yapp/domain/auth/presentation/dto/response/SmsVerifyResponse.java, api/src/main/java/org/yapp/domain/user/application/UserService.java, api/src/main/java/org/yapp/domain/user/dao/UserRepository.java, core/exception/src/main/java/org/yapp/core/exception/error/code/UserErrorCode.java
[PC-813]
- 동일 번호 중복 가입 여부 확인 로직 구현
- 인증번호 API에서 중복 가입 여부 검사
[PC-813]: https://yapp25app3.atlassian.net/browse/PC-813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-813] 동일 번호 중복 가입 방지

api/src/main/java/org/yapp/domain/setting/presentation/SettingController.java
[PC-852] 
- 알림 설정 오타 수정
[PC-852]: https://yapp25app3.atlassian.net/browse/PC-852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-852] hotfix: 알림 설정 오타 수정

api/src/main/java/org/yapp/domain/user/application/UserService.java
[PC-908]
- 정지 유저 재가입 방지로직에서 에러처리
[PC-908]: https://yapp25app3.atlassian.net/browse/PC-908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-908] 정지 유저 재가입 방지로직에서 에러처리

api/src/main/java/org/yapp/global/config/GoogleOauthConfig.java
[PC-961]
- google Oauth 설정에 ios 클라이언트 추가
[PC-961]: https://yapp25app3.atlassian.net/browse/PC-961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-961] google Oauth 설정에 ios 클라이언트 추가

admin/src/main/java/org/yapp/match/application/query/ManualMatchHistoryQueryService.java
[PC-1076]
- 닉네임 출력 안되는 문제 해결
[PC-1076]: https://yapp25app3.atlassian.net/browse/PC-1076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-1076] 닉네임 출력 안되는 문제 해결

admin/src/main/java/org/yapp/match/application/command/ManualMatchCommandService.java, admin/src/main/java/org/yapp/notification/application/AdminNotificationService.java, api/src/main/java/org/yapp/domain/notification/application/ApiNotificationService.java, core/notification/src/main/java/org/yapp/core/notification/application/NotificationService.java
[PC-1155]
- 알람 메시지 수정
- 수동 매칭 날짜 지정한 날짜로 저장
[PC-1155]: https://yapp25app3.atlassian.net/browse/PC-1155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-1155] UX writing 수정 대응 및 수동 매칭 날짜 수정
