YAPP-Github/Piece-Server

api/src/main/java/org/yapp/domain/auth/application/oauth/service/OauthService.java
api/src/main/java/org/yapp/domain/profile/api/ProfileController.java
api/src/main/java/org/yapp/domain/profile/api/request/ProfileUpdateRequest.java
api/src/main/java/org/yapp/domain/profile/api/response/ProfileResponse.java
api/src/main/java/org/yapp/domain/profile/api/response/ProfileValueResponse.java
api/src/main/java/org/yapp/domain/profile/application/ProfileService.java
api/src/main/java/org/yapp/domain/profile/application/dto/ProfileCreateDto.java
api/src/main/java/org/yapp/domain/profile/application/util/NickNameGenerator.java
api/src/main/java/org/yapp/domain/profile/dao/ProfileRepository.java
api/src/main/java/org/yapp/domain/user/application/UserService.java
api/src/main/java/org/yapp/domain/user/dao/UserRepository.java
api/src/main/java/org/yapp/domain/user/domain/User.java
api/src/main/java/org/yapp/global/config/SecurityConfig.java
api/src/test/java/org/yapp/domain/auth/application/oauth/service/OauthServiceTest.java
api/src/test/java/org/yapp/domain/auth/application/profile/ProfileServiceTest.java
common/build.gradle
common/src/main/java/org/yapp/domain/profile/Profile.java
common/src/main/java/org/yapp/domain/profile/ProfileBasic.java
common/src/main/java/org/yapp/domain/profile/ProfileBio.java
common/src/main/java/org/yapp/domain/profile/ProfileValue.java
common/src/main/java/org/yapp/domain/profile/ValueItem.java
common/src/main/java/org/yapp/domain/user/User.java
common/src/main/java/org/yapp/error/dto/ProfileErrorCode.java
common/src/main/java/org/yapp/error/dto/UserErrorCode.java
common/src/main/java/org/yapp/error/exception/ApplicationException.java
common/src/main/java/org/yapp/util/ApiResponse.java

티켓: #PC-80
깃이슈: #6 
- 프로필 (기본, 소개글) 생성/수정 기능
- KakaoOauthProviderTest가 테스트 실패하는데 확인 부탁드립니다.
- api 모듈에 user 클래스가 있는데, common 모듈에서 관리하는게 나을 거 같아서, api 모듈에 있던 user 클래스는 일단 주석 처리해놨고 common에 새로 만들어서 작업했습니다

Feature: 유저 프로필 (기본, 소개글) 생성/수정 (#PC-80)

---

api/src/main/java/org/yapp/domain/auth/api/LoginController.java
api/src/main/java/org/yapp/domain/auth/application/oauth/google/GoogleOauthClient.java
api/src/main/java/org/yapp/domain/auth/application/oauth/service/OauthService.java
api/src/main/java/org/yapp/domain/auth/presentation/LoginController.java
api/src/main/java/org/yapp/domain/auth/presentation/dto/request/OauthLoginRequest.java
api/src/main/java/org/yapp/domain/auth/presentation/dto/response/OauthLoginResponse.java
api/src/main/java/org/yapp/domain/auth/presentation/dto/response/OauthUserInfoResponse.java
api/src/main/java/org/yapp/domain/profile/api/ProfileController.java
api/src/main/java/org/yapp/domain/value/presentation/ValueItemController.java
api/src/main/java/org/yapp/global/config/GoogleOauthConfig.java
api/src/test/java/org/yapp/domain/auth/application/oauth/google/GoogleOauthClientTest.java
api/src/test/java/org/yapp/domain/auth/application/oauth/service/OauthServiceTest.java
build.gradle
common/src/main/java/org/yapp/error/code/auth/AuthErrorCode.java
common/src/main/java/org/yapp/util/CommonResponse.java

[PC-203](https://yapp25app3.atlassian.net/browse/PC-203)
- google oauth client 라이브러리 추가
- google oauth 인증 방식 변경
- 액세스 토큰 방식 -> IdToken 방식
- OauthErrorCode 추가
- ApiResponse 객체 이름 변경 -> CommonResponse
- ApiResponse 클래스가 Swagger 에서 사용하는 클래스의 이름과 같아서 CommonResponse 로 변경하였습니다.
[PC-203]: https://yapp25app3.atlassian.net/browse/PC-203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-203] Google Oauth 인증 IdToken 인증하는 로직으로 변경

---

api/src/main/java/org/yapp/domain/profile/application/ProfileService.java
api/src/main/java/org/yapp/domain/profile/dao/ProfileValueRepository.java
api/src/main/java/org/yapp/domain/profile/presentation/ProfileController.java
api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileValuePair.java
api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileValueUpdateRequest.java
api/src/test/java/org/yapp/domain/auth/application/profile/ProfileServiceTest.java
common/src/main/java/org/yapp/domain/profile/Profile.java
common/src/main/java/org/yapp/domain/profile/ProfileValue.java

[PC-71](https://yapp25app3.atlassian.net/browse/PC-71)
- 프로필 가치관 업데이트 기능 개발
- 프로필 가치관 업데이트 기능 테스트
이번에 테스트를 위한 DB로 H2를 적용하려고 했는데 문제가 생겼습니다..  ValueItem 엔티티에 Json 매핑용 Map 타입을 사용하는데 MySQL 에서는 호환 가능하지만 H2에서는 호환이 안됩니다..
H2를 위해서는  필드 타입을 Map이 아닌 String으로 변환하고 직접 컨버팅 하는 방식으로 수정이 필요할 것 같습니다. 다른 방식으로는 인메모리 DB가 아닌 외부 MySQL DB를 테스트 용으로 구축하는 방안도 있을 것 같습니다.  
[PC-71]: https://yapp25app3.atlassian.net/browse/PC-71?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-71] 프로필 가치관 업데이트 기능

---

api/src/main/java/org/yapp/domain/profile/application/ProfileImageService.java
api/src/main/java/org/yapp/domain/profile/presentation/ProfileController.java
api/src/main/resources/application.yml
build.gradle
common/src/main/java/org/yapp/config/S3Config.java
common/src/main/java/org/yapp/infra/s3/application/S3Service.java

[PC-194](https://yapp25app3.atlassian.net/browse/PC-194)
- 파일 업로드 / 삭제를 위한 S3 서비스 클래스 개발
- 프로필 이미지 업로드를 위한 서비스 클래스 개발
- 프로필 이미지 업로드를 위한 컨트롤러 개발
- 버킷은 임시용으로 테스트하기 위해 회사에서 사용하고 있던 버킷을 사용했습니다,,
[PC-194]: https://yapp25app3.atlassian.net/browse/PC-194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-194] 이미지 등록 API

---

api/src/main/java/org/yapp/domain/auth/application/authorization/SmsAuthService.java
api/src/main/java/org/yapp/domain/auth/application/oauth/service/OauthService.java
api/src/main/java/org/yapp/domain/auth/presentation/LoginController.java
api/src/main/java/org/yapp/domain/auth/presentation/SmsAuthController.java
api/src/main/java/org/yapp/domain/auth/presentation/dto/enums/RoleStatus.java
api/src/main/java/org/yapp/domain/auth/presentation/dto/request/SmsAuthRequest.java
api/src/main/java/org/yapp/domain/auth/presentation/dto/request/SmsAuthVerifyRequest.java
api/src/main/java/org/yapp/domain/auth/presentation/dto/response/OauthLoginResponse.java
api/src/main/java/org/yapp/domain/profile/presentation/ProfileController.java
api/src/main/java/org/yapp/domain/user/application/UserService.java
api/src/main/java/org/yapp/global/application/RedisService.java
api/src/main/java/org/yapp/global/config/SecurityConfig.java
api/src/test/java/org/yapp/domain/auth/application/authorization/SmsAuthServiceTest.java
api/src/test/java/org/yapp/domain/auth/application/oauth/service/OauthServiceTest.java
build.gradle
common/src/main/java/org/yapp/application/AuthenticationService.java
common/src/main/java/org/yapp/config/RedisConfig.java
common/src/main/java/org/yapp/domain/user/User.java
common/src/main/java/org/yapp/error/code/auth/SmsAuthErrorCode.java

- 인증번호 검증 로직 추가
- redis를 통해 인증번호에 TTL 설정 - 5분
- Role 기반 인증 단계 인식 기능 추가
- RedisService 추가
- sms 인증/검증 엔드포인트 추가
- 프로필 초기화 기능 추가
- 프로필 생성 로직을 논의해서 수정할 필요가 있을 것 같습니다
- 닉네임 자동생성 중복 검사 로직

[PC-214] 회원가입 절차에 SMS 인증번호 검증 로직 추가

---

api/src/main/java/org/yapp/domain/term/applicatoin/TermService.java
api/src/main/java/org/yapp/domain/term/applicatoin/TermUseCase.java
api/src/main/java/org/yapp/domain/term/applicatoin/dto/SignupTermsDto.java
api/src/main/java/org/yapp/domain/term/dao/TermAgreementRepository.java
api/src/main/java/org/yapp/domain/term/dao/TermRepository.java
api/src/main/java/org/yapp/domain/term/presentation/TermController.java
api/src/main/java/org/yapp/domain/term/presentation/dto/response/TermResponse.java
api/src/main/java/org/yapp/domain/term/presentation/dto/response/TermResponses.java
api/src/main/resources/init.sql
api/src/test/java/org/yapp/domain/auth/application/term/TermUseCaseTest.java
common/src/main/java/org/yapp/domain/term/Term.java
common/src/main/java/org/yapp/domain/term/TermAgreement.java
common/src/main/java/org/yapp/error/dto/TermErrorCode.java

[PC-197](https://yapp25app3.atlassian.net/browse/PC-197)
- 서비스 등록 약관 조회 기능
- 회원가입시 약관 등록 기능
서비스 등록 약관 조회 기능은 더미 데이터를 활용해서 API를 테스트해봤는데, 회원가입시 사용자 약관을 등록하는 로직은 실제로 클라이언트와 연동하면서 테스트하는 것이 나을 것 같습니다. 
[PC-197]: https://yapp25app3.atlassian.net/browse/PC-197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-197] 약관 기능

---

api/src/main/java/org/yapp/domain/block/application/DirectBlockService.java
api/src/main/java/org/yapp/domain/block/dao/DirectBlockRepository.java
api/src/main/java/org/yapp/domain/match/application/blocker/DirectBlockBasedBlocker.java
api/src/main/java/org/yapp/domain/match/presentation/MatchController.java
common/src/main/java/org/yapp/domain/block/DirectBlock.java

[PC-273](https://yapp25app3.atlassian.net/browse/PC-273)
- 매칭 상대 차단 기능 구현
- 매칭 상대 차단기 구현 및 매칭 로직에 적용
[PC-273]: https://yapp25app3.atlassian.net/browse/PC-273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-273] 매칭 상대 차단 기능 구현

---

api/src/main/java/org/yapp/domain/block/application/DirectBlockService.java
api/src/main/java/org/yapp/domain/block/dao/DirectBlockRepository.java
api/src/main/java/org/yapp/domain/match/application/MatchService.java
api/src/main/java/org/yapp/domain/match/application/blocker/DirectBlockBasedBlocker.java
api/src/main/java/org/yapp/domain/match/presentation/MatchController.java
api/src/main/java/org/yapp/domain/match/presentation/dto/response/ContactResponse.java
api/src/main/java/org/yapp/domain/match/presentation/dto/response/ImageUrlResponse.java
api/src/main/java/org/yapp/domain/match/presentation/dto/response/MatchInfoResponse.java
api/src/main/java/org/yapp/domain/match/presentation/dto/response/MatchProfileBasicResponse.java
api/src/main/java/org/yapp/domain/match/presentation/dto/response/MatchValuePickInnerResponse.java
api/src/main/java/org/yapp/domain/match/presentation/dto/response/MatchValuePickResponse.java
api/src/main/java/org/yapp/domain/match/presentation/dto/response/MatchValueTalkInnerResponse.java
api/src/main/java/org/yapp/domain/match/presentation/dto/response/MatchValueTalkResponse.java
common/src/main/java/org/yapp/domain/block/DirectBlock.java
common/src/main/java/org/yapp/domain/match/MatchInfo.java
common/src/main/java/org/yapp/domain/match/enums/MatchStatus.java
common/src/main/java/org/yapp/error/dto/MatchErrorCode.java

[PC-270](https://yapp25app3.atlassian.net/browse/PC-270)
- 매칭 정보 조회 기능 구현
- 매칭 조각 확인 체크 기능 구현
- 매칭 프로필 기본 정보 확인 기능 구현
- 매칭 상대 가치관 톡 확인 기능 구현
- 매칭 상대 가치관 픽 확인 기능 구현
- 매칭 상대 프로필 이미지 확인 기능 구현
- 나를 표현하는 한마디가 Deprecated된 ProfileBIO안에 있는 것 같습니다. 해당 정보를 이제 어디에 저장할지 생각해봐야 할 것 같습니다.
[PC-270]: https://yapp25app3.atlassian.net/browse/PC-270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-270] 매칭 조각 확인 기능 구현

---

admin/build.gradle
admin/src/main/java/org/yapp/auth/application/AdminRole.java
admin/src/main/java/org/yapp/auth/application/AuthService.java
admin/src/main/java/org/yapp/auth/application/dto/LoginDto.java
admin/src/main/java/org/yapp/auth/presentation/AuthController.java
admin/src/main/java/org/yapp/auth/presentation/request/LoginRequest.java
admin/src/main/java/org/yapp/config/SecurityConfig.java
admin/src/main/java/org/yapp/user/application/UserService.java
admin/src/main/java/org/yapp/user/dao/UserRepository.java
admin/src/main/resources/application.yml
common/auth/build.gradle
common/auth/src/main/java/org/yapp/auth/AuthToken.java
common/auth/src/main/java/org/yapp/auth/AuthTokenGenerator.java
common/auth/src/main/java/org/yapp/jwt/JwtFilter.java
common/auth/src/main/java/org/yapp/jwt/JwtUtil.java
common/exception/src/main/java/org/yapp/error/code/auth/AuthErrorCode.java
settings.gradle

[PC-379](https://yapp25app3.atlassian.net/browse/PC-379)
- api 모듈에 있던 jwt 기능을 common:auth 모듈로 리팩토링
- common:auth에 Token 생성 기능 추가
- admin 모듈 로그인 기능
로그인하는 사용자를 위해 common:auth 모듈을 만들고 admin 모듈에서는 common:auth를 사용하도록 하였습니다.
토큰을 생성하는 로직을 api 모듈에서도 common:auth 기능을 사용하도록 수정해야합니다.
[PC-379]: https://yapp25app3.atlassian.net/browse/PC-379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-379] 어드민 모듈 로그인 기능

---

api/build.gradle
api/src/main/java/org/yapp/domain/profile/application/ProfileImageService.java
api/src/main/java/org/yapp/domain/profile/presentation/ProfileController.java
api/src/main/java/org/yapp/global/config/SecurityConfig.java
api/src/main/java/org/yapp/sse/presentation/SseController.java
core/exception/src/main/java/org/yapp/core/exception/error/code/ProfileErrorCode.java
core/sse/build.gradle
core/sse/src/main/java/org/yapp/core/sse/FluxSsePersonalService.java
core/sse/src/main/java/org/yapp/core/sse/SsePersonalService.java
core/sse/src/main/java/org/yapp/core/sse/dto/EventType.java
core/sse/src/main/java/org/yapp/core/sse/dto/SsePayload.java
settings.gradle

[PC-478](https://yapp25app3.atlassian.net/browse/PC-478)
- core:sse 모듈 생성
- SsePersionalService 인터페이스 생성
- FluxSsePersionalService 구현체 생성
- sse 연결 API 구현
@PreAuthorize(value = "hasRole('USER')")
이렇게 sse 연결 api에 USER 권한을 가진 회원만 접근가능하도록 설정했는데, 저게 작동을 안 하는 것 같아요.
Authorization 헤더에 빈 값을 넣고 요청을 보내면 내부에서 userId가 null 이라고 에러를 뱉네요 ,,
[PC-478]: https://yapp25app3.atlassian.net/browse/PC-478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-478] SSE Flux 구현

---

api/src/main/java/org/yapp/domain/auth/presentation/SmsAuthController.java
api/src/main/java/org/yapp/domain/profile/application/ProfileValueTalkSummaryService.java
api/src/main/java/org/yapp/domain/profile/presentation/ProfileController.java
api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileTalkSummaryUpdateRequest.java
api/src/main/java/org/yapp/domain/user/application/UserService.java
api/src/main/java/org/yapp/sse/presentation/SseController.java
core/sse/src/main/java/org/yapp/core/sse/FluxSsePersonalService.java
infra/ai/src/main/java/org/yapp/infra/ai/application/ClovaChatSummarizationService.java

[PC-545](https://yapp25app3.atlassian.net/browse/PC-545)
- UserService에서 AuthenticationService를 사용하지 안도록 변경
- AI 요약 동기 / 비동기 구분
- 프로필 생성시 AI 요약 동기 진행
- Sse FluxSink 적용 
- 프로필 요약 데이터를 여러 쓰레드에서 전달하기 위해, thread-safe한 Sse FluxSink로 sink를 변경하였습니다. 
[PC-545]: https://yapp25app3.atlassian.net/browse/PC-545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-545] 프로필 생성시 AI 요약

---

api/src/main/java/org/yapp/domain/auth/application/oauth/service/OauthService.java
api/src/main/java/org/yapp/domain/match/application/algorithm/GreedyMatchingAlgorithm.java
api/src/main/java/org/yapp/domain/match/application/blocker/AcquaintanceBasedBlocker.java
api/src/main/java/org/yapp/domain/setting/application/SettingService.java
api/src/main/java/org/yapp/domain/setting/dao/SettingRepository.java
api/src/main/java/org/yapp/domain/setting/dto/SettingInfoResponse.java
api/src/main/java/org/yapp/domain/setting/dto/request/SettingToggleRequest.java
api/src/main/java/org/yapp/domain/setting/dto/response/SettingInfoResponse.java
api/src/main/java/org/yapp/domain/setting/presentation/SettingController.java
core/domain/src/main/java/org/yapp/core/domain/setting/Setting.java
core/exception/src/main/java/org/yapp/core/exception/error/code/SettingErrorCode.java

[PC-416](https://yapp25app3.atlassian.net/browse/PC-416)
- 세팅 엔티티 추가
- 유저 세팅 정보 확인 기능 구현
- 알림 토글 온오프 기능 구현
- 지인 차단 온오프 기능 구현
- 회원가입시 유저 설정 정보 추가
[PC-416]: https://yapp25app3.atlassian.net/browse/PC-416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-416] 유저 설정 기능 구현

---

api/src/main/java/org/yapp/domain/profile/presentation/response/ProfileValueTalkResponse.java
api/src/main/java/org/yapp/domain/profile/presentation/response/ProfileValueTalkResponses.java

[PC-580]
- 프로필 가치관 톡 조회시 guides와 placeholder 데이터를 추가로 전달합니다.
[PC-580]: https://yapp25app3.atlassian.net/browse/PC-580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-580] 프로필 가치관 톡 조회 응답 형식 변경

---

api/build.gradle
api/src/main/java/org/yapp/domain/auth/application/oauth/apple/AppleIdTokenDecoder.java
api/src/main/java/org/yapp/domain/auth/application/oauth/apple/AppleOauthClient.java
api/src/main/java/org/yapp/domain/auth/application/oauth/apple/AppleOauthHelper.java
api/src/main/java/org/yapp/domain/auth/application/oauth/apple/AppleOauthProvider.java
api/src/main/java/org/yapp/domain/auth/application/oauth/apple/dto/AppleAuthResponse.java
api/src/main/java/org/yapp/domain/auth/application/oauth/service/OauthService.java
api/src/main/java/org/yapp/domain/auth/domain/enums/OauthType.java
api/src/main/java/org/yapp/domain/auth/presentation/dto/request/OauthLoginRequest.java
api/src/main/java/org/yapp/global/config/AppleOauthProperties.java
core/domain/src/main/java/org/yapp/core/domain/auth/RefreshToken.java
core/exception/src/main/java/org/yapp/core/exception/error/code/AuthErrorCode.java

[PC-175](https://yapp25app3.atlassian.net/browse/PC-175)
- OauthLoginRequest 필드 이름 수정 (token -> oauthCredential)
- 리프레쉬 토근 길이 수정
- 애플 로그인 기능
애플 로그인의 경우 토큰이 아니라, Authorization code 값을 전달 받기 떄문에 OauthLoginRequest에서 token 필드의 이름을 추상화하여 oauthCredential로 변경하였씁니다. 
[PC-175]: https://yapp25app3.atlassian.net/browse/PC-175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-175] 애플 소셜 로그인 기능 

---

api/src/main/java/org/yapp/domain/user/application/UserService.java
api/src/main/java/org/yapp/domain/user/presentation/UserController.java
core/domain/src/main/java/org/yapp/core/domain/block/BlockContact.java
core/domain/src/main/java/org/yapp/core/domain/match/MatchInfo.java
core/domain/src/main/java/org/yapp/core/domain/report/Report.java
core/domain/src/main/java/org/yapp/core/domain/term/TermAgreement.java
core/domain/src/main/java/org/yapp/core/domain/user/User.java
core/domain/src/main/java/org/yapp/core/domain/user/UserRejectHistory.java

[PC-607](https://yapp25app3.atlassian.net/browse/PC-607)
- onDelete Cascade 설정
- 회원 탈퇴 기능 구현
- 회원 탈퇴 API 엔드포인트 추가
[PC-607]: https://yapp25app3.atlassian.net/browse/PC-607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-607] 회원 탈퇴 기능 구현

---

api/src/main/java/org/yapp/domain/block/application/DirectBlockService.java
api/src/main/java/org/yapp/domain/match/application/MatchService.java
api/src/main/java/org/yapp/domain/match/presentation/MatchController.java
api/src/main/java/org/yapp/domain/match/presentation/dto/request/MatchBlockRequest.java
api/src/main/java/org/yapp/domain/match/presentation/dto/response/MatchInfoResponse.java
api/src/main/java/org/yapp/domain/profile/application/ProfileValueTalkSummaryService.java
core/domain/src/main/java/org/yapp/core/domain/match/MatchInfo.java
core/domain/src/main/java/org/yapp/core/domain/match/enums/UserMatchStatus.java

[PC-612](https://yapp25app3.atlassian.net/browse/PC-612) 
- AI 요약 데이터가 50자를 초과하는 경우 넘는 만큼의 분량 절삭
- (/api/matched/infos)의 응답에 isBlocked 필드 추가
[PC-612]: https://yapp25app3.atlassian.net/browse/PC-612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-612] 매칭 차단 정보 추가

---

api/src/main/java/org/yapp/domain/user/application/UserService.java
api/src/main/java/org/yapp/domain/user/dao/UserDeleteReasonRepository.java
api/src/main/java/org/yapp/domain/user/presentation/UserController.java
api/src/main/java/org/yapp/domain/user/presentation/dto/request/UserDeleteRequest.java
api/src/main/java/org/yapp/domain/user/presentation/dto/response/UserRejectHistoryResponse.java
core/domain/src/main/java/org/yapp/core/domain/user/UserDeleteReason.java

[PC-615](https://yapp25app3.atlassian.net/browse/PC-615)
- 회원 탈퇴 이유 저장 기능 구현
[PC-615]: https://yapp25app3.atlassian.net/browse/PC-615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-615] 회원 탈퇴 이유 저장

---

api/src/main/java/org/yapp/domain/profile/application/ProfileService.java
api/src/main/java/org/yapp/domain/profile/presentation/ProfileController.java
api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileCreateRequest.java
api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileUpdateRequest.java
api/src/main/java/org/yapp/domain/profile/presentation/validation/ContactTypeValidator.java
api/src/main/java/org/yapp/domain/user/application/UserService.java
api/src/main/java/org/yapp/domain/user/presentation/dto/response/UserBasicInfoResponse.java
api/src/main/java/org/yapp/domain/user/presentation/dto/response/UserRejectHistoryResponse.java
api/src/main/java/org/yapp/sse/presentation/SseController.java
core/domain/src/main/java/org/yapp/core/domain/profile/Profile.java
infra/s3/src/main/java/org/yapp/infra/s3/application/S3Service.java
infra/s3/src/main/java/org/yapp/infra/s3/config/S3Config.java

- SSE 권한 체크 수정 (hasRole -> hasAuthority)
- 사용자 기본 정보 조회 API 응답에서 profileStatus 추가
- 리젝 사유 조회 응답 수정
- 오브젝트 스토리지 변경 (AWS S3 사용)
- 프로필 연락처 검증 로직 수정 (연락처 최소 1개 이상)
- 프로필 반려시 프로필 수정 기능
- 오브젝트 스토리지 변경으로 인해, 기존에 설정해주었던 s3 endpoint와 필요없게 되었고, access-key와 secret-key가 변경되었습니다. 
notion에 정리해둔 .yml 파일을 참고해서 찬호님 개발환경에도 반영하시면 될 것 같습니다.

[PC-000] SSE 요청 권한 수정 및 사용자 기본 정보 응답 포맷 수정

---

api/src/main/java/org/yapp/domain/auth/application/oauth/service/LogoutService.java
api/src/main/java/org/yapp/domain/user/application/UserService.java
api/src/main/java/org/yapp/domain/user/dao/FcmTokenRepository.java
api/src/main/java/org/yapp/domain/user/presentation/UserController.java
api/src/main/java/org/yapp/domain/user/presentation/dto/request/FcmTokenSaveRequest.java
core/auth/src/main/java/org/yapp/core/auth/jwt/JwtFilter.java
core/domain/src/main/java/org/yapp/core/domain/fcm/FcmToken.java
core/exception/src/main/java/org/yapp/core/exception/error/code/AuthErrorCode.java

[PC-684]
- FCM 토큰 저장, 삭제 기능 구현
- FCM 토큰 저장 API 추가
- 로그아웃 시 FCM 토큰 삭제하도록 로직 추가
- 필터단 에러 응답을 RestAdvice 계층과 통일
- 필터단 에러응답의 인코딩 설정
[PC-684]: https://yapp25app3.atlassian.net/browse/PC-684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-684] FCM 토큰 관련 기능 구현

---

admin/build.gradle
admin/src/main/java/org/yapp/ban/application/BanModifyingService.java
admin/src/main/java/org/yapp/ban/application/BanService.java
admin/src/main/java/org/yapp/ban/presentation/BanController.java
admin/src/main/java/org/yapp/ban/presentation/dto/request/UserBanRequest.java
api/src/main/java/org/yapp/domain/auth/application/oauth/service/OauthService.java
api/src/main/java/org/yapp/domain/auth/presentation/LoginController.java
api/src/main/java/org/yapp/domain/user/application/BanCheckingService.java
api/src/main/java/org/yapp/domain/user/application/UserService.java
api/src/main/java/org/yapp/global/config/InterceptorConfig.java
api/src/main/java/org/yapp/global/interceptor/BanCheckingInterceptor.java
core/auth/src/main/java/org/yapp/core/auth/dao/BannedUserPhoneNumberRepository.java
core/domain/src/main/java/org/yapp/core/domain/user/BannedUserPhoneNumber.java
core/domain/src/main/java/org/yapp/core/domain/user/RoleStatus.java
core/exception/src/main/java/org/yapp/core/exception/error/code/AuthErrorCode.java
infra/redis/src/main/java/org/yapp/infra/redis/application/RedisService.java

[PC-900]
- 유저 정지 기능과 어드민 API 구현
- 유저 정지 여부 판단 인터셉터 추가
- 정지된 유저의 재가입 방지로직 추가
- 정지 유저의 리프레시 방지 로직 추가
[PC-900]: https://yapp25app3.atlassian.net/browse/PC-900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-900] 유저 정지 기능 구현

---

api/src/main/java/org/yapp/domain/auth/application/authorization/SmsAuthService.java
api/src/main/java/org/yapp/domain/setting/dto/response/BlockContactSyncTimeResponse.java
api/src/main/java/org/yapp/domain/setting/dto/serializer/BlockContactSyncTimeResponseSerializer.java

[PC-921]
- SMS 인증코드 자리수 관련 문제 해결
- 연락처 동기화 시간 관련 IOS직렬화 이슈 대응 위해 커스텀 JSON Serializer 적용
[PC-907]: https://yapp25app3.atlassian.net/browse/PC-907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PC-921]: https://yapp25app3.atlassian.net/browse/PC-921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-921] SMS 인증코드 버그 픽스 및 IOS 직렬화 이슈 대응

---

api/src/main/java/org/yapp/domain/auth/application/authorization/AuthCodeGenerator.java
api/src/main/java/org/yapp/domain/auth/application/authorization/SmsAuthService.java
api/src/test/java/org/yapp/domain/auth/application/authorization/AuthCodeGeneratorTest.java
api/src/test/java/org/yapp/domain/auth/application/authorization/SmsAuthServiceTest.java

[PC-921]
- AuthCodeGenerator 에서 String을 반환하도록 변경한 부분이 누락되어 다시 PR올립니다
[PC-907]: https://yapp25app3.atlassian.net/browse/PC-907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PC-921]: https://yapp25app3.atlassian.net/browse/PC-921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-921] AuthCodeGenerator 에서 String을 반환하도록 변경

---

admin/src/main/java/org/yapp/notification/application/AdminNotificationService.java
admin/src/main/java/org/yapp/profile/application/AdminProfileImageService.java
admin/src/main/java/org/yapp/profile/application/AdminProfileService.java
admin/src/main/java/org/yapp/profile/dao/ProfileImageRepository.java
admin/src/main/java/org/yapp/profile/presentation/ProfileImagesController.java
admin/src/main/java/org/yapp/profile/presentation/request/UpdateProfileImageStatusRequest.java
admin/src/main/java/org/yapp/user/application/UserService.java
admin/src/main/java/org/yapp/user/presentation/UserController.java
admin/src/main/java/org/yapp/user/presentation/request/UpdateProfileStatusRequest.java
admin/src/main/java/org/yapp/user/presentation/response/UserProfileImageDetailResponse.java
admin/src/main/java/org/yapp/user/presentation/response/UserProfileImageResponse.java
admin/src/main/java/org/yapp/user/presentation/response/UserProfileValidationResponse.java
api/src/main/java/org/yapp/domain/profile/application/ProfileImageService.java
api/src/main/java/org/yapp/domain/profile/application/ProfileService.java
api/src/main/java/org/yapp/domain/profile/application/dto/ProfileImageDto.java
api/src/main/java/org/yapp/domain/profile/dao/ProfileImageRepository.java
api/src/main/java/org/yapp/domain/profile/presentation/ProfileController.java
api/src/main/java/org/yapp/domain/profile/presentation/response/ProfileBasicResponse.java
core/domain/src/main/java/org/yapp/core/domain/notification/enums/NotificationType.java
core/domain/src/main/java/org/yapp/core/domain/profile/Profile.java
core/domain/src/main/java/org/yapp/core/domain/profile/ProfileBasic.java
core/domain/src/main/java/org/yapp/core/domain/profile/ProfileImage.java
core/domain/src/main/java/org/yapp/core/domain/profile/ProfileImageStatus.java
core/exception/src/main/java/org/yapp/core/exception/error/code/ProfileImageErrorCode.java

[PC-876](https://yapp25app3.atlassian.net/browse/PC-876)
- **ProfileImage 테이블 생성**
- 사용자가 프로필 생성을 완료한 뒤 시점부터, 변경하는 이미지가 저장되는 테이블입니다.
- 각 프로필 이미지는 아래의 3가지 상태를 가집니다:
- `PENDING`
- `ACCEPTED`
- `REJECTED`
- `ProfileBasic` 클래스의 `imageUrl`은 가장 최근에 **승인된 프로필 이미지**라고 생각하면 됩니다.
- **기능 추가**
- 프로필 이미지 수정 시 Discord Notification 발송
- 자신의 프로필 Basic 정보 조회 시 `pendingImageUrl` 전달
- 심사진행 중인 이미지가 있는 경우, 심사 중인 이미지를 함께 전달 (`pendingImageUrl` 필드 포함)
- **프로필 이미지 심사 기능 추가**
- **프로필 이미지 데이터 조회 기능 추가**
- **프로필 이미지 수정 시 Discord Notification 발송**
- **자신의 프로필 Basic 조회 시 `pendingImageUrl` 전달**
- 심사진행 중인 이미지가 있을 경우, 해당 이미지도 함께 반환
- 필드명: `pendingImageUrl`
- **사용자 정보 페이지네이션 API에 `profileStatus` 필드 추가**
[PC-876]: https://yapp25app3.atlassian.net/browse/PC-876?atlOrigin=eyJpIjoiNWR …

[PC-876] 수정된 프로필 이미지 심사

---

admin/src/main/java/org/yapp/notification/application/AdminNotificationService.java
admin/src/main/java/org/yapp/profile/application/AdminProfileImageService.java
admin/src/main/java/org/yapp/user/application/UserService.java
admin/src/main/java/org/yapp/user/dao/UserRepository.java
admin/src/main/java/org/yapp/user/presentation/UserController.java
api/src/main/java/org/yapp/domain/user/presentation/dto/request/OauthUserDeleteRequest.java
api/src/main/resources/application.yml
core/notification/src/main/java/org/yapp/core/notification/application/NotificationService.java

[PC-964](https://yapp25app3.atlassian.net/browse/PC-964)
- 유저 ID, 프로필 ID, 닉네임으로 유저 조회
- NotificationService#sendNotification 
- 트랜잭션 전파 설정 변경 (Propagation.REQUIRES_NEW)
- FCM 에외 발생을 외부로 전파시키지 않도록 설정
[PC-964]: https://yapp25app3.atlassian.net/browse/PC-964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-964] 어드민 유저 검색 기능 및 FCM 예외 처리 변경

---

api/src/main/java/org/yapp/domain/user/application/UserService.java
api/src/main/java/org/yapp/domain/user/presentation/UserController.java
api/src/main/java/org/yapp/domain/user/presentation/dto/response/UserBasicInfoResponse.java
core/auth/src/main/java/org/yapp/core/auth/AuthUtil.java

[PC-1007]
- 토큰 내부의 role과 유저 role의 불일치를 해결하기 위해 user info 조회에서 role 변경을 알 수 있도록 필드를 추가하였습니다.
- 클라이언트 측의 요청에 따라 role 불일치가 발생했을 때 user info API에서 바로 role이 갱신된 jwtToken을 반환하도록 필드를 추가하였습니다.
[PC-1007]: https://yapp25app3.atlassian.net/browse/PC-1007?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-1007] 유저 정보 API에서 role 변경시 토큰 재발급

---

api/src/main/java/org/yapp/domain/setting/application/SettingService.java
api/src/main/java/org/yapp/domain/setting/dto/response/SettingInfoResponse.java

[PC-1136]
- 매칭 설정 필드 삭제했습니다.
[PC-1136]: https://yapp25app3.atlassian.net/browse/PC-1136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-1136] 매칭 설정 필드 삭제

---

api/src/main/java/org/yapp/domain/match/application/algorithm/GreedyMatchAlgorithm.java
api/src/main/java/org/yapp/domain/match/application/algorithm/preference/AgePreferenceCalculatingPolicy.java

[PC-1254]
- 하루한번 매칭 시 가중치에 나이 차이에 따른 가중치를 적용하였습니다.
- 가중치 계산시 각 가중치 계산 로직을 순회하는 방식으로 변경하였습니다. 
[PC-1254]: https://yapp25app3.atlassian.net/browse/PC-1254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-1254] 나이별 가중치 적용
